# Generated by Django 4.1.2 on 2022-10-14 08:07

from django.db import migrations, models
import gamesplay_app.game.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Puzzle'), (4, 'Strategy'), (5, 'Sports'), (6, 'Board/Card Game'), (7, 'Other')], max_length=15)),
                ('rating', models.FloatField(max_length=5.0, validators=[gamesplay_app.game.validators.validate_rating_min])),
                ('max_level', models.IntegerField(blank=True, null=True, validators=[gamesplay_app.game.validators.validate_max_level])),
                ('image', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
